version: "3.9"
services:
  web:
    image: 3run01/urano:v-3.0
    container_name: filament
    volumes:
      - .:/var/www/app
      - ./docker/php/extra-php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8022:80" #httpdoc
#      - "5173:5173" #httpdoc
      #- "443:443" #https
#    restart: always
    networks:
      - desenvolvimento
networks:
  desenvolvimento:
    external: true
